### PR TITLE
Reorganization of user guide content (state propagation + environment setup)

### PR DESCRIPTION
**Pull request by FilippoOggionni**
I started reorganizing some content in the state propagation part of the user guide. 

This is my proposal, I moved quite a lot of content into new pages. For now, I worked on the state propagation overview page ([here](https://tudat-space.readthedocs.io/en/latest/_src_user_guide/state_propagation.html#propagator-setup)) and on the environment pages. I also created two new diagrams included in my changes  (I have the raw files, so they can be modified). The propagation and numerical integration parts are still work in progress. 

It is of course very difficult to have the entire user guide ready before the first lecture of Numerical Astrodynamics, but this was never the goal. It is up to you @DominicDirkx to decide whether this pull request can be merged as soon as its content is reviewed by you (and if he has time by @jo11he) or to wait until the entire user guide is reorganized.

### CODE REVIEW

**Comment by FilippoOggionni** [comment]
What I don't like of this solution is the way it is shown in the TOC on the left side. With my proposal, there is only one level depth in the TOC, so a user has to navigate manually through the pages. However, I am confident that this can be solved somehow, maintaining the new organization. I have not spent time researching the issue though.

Screen Shot 2021-11-06 at 19 56 24

**Comment by FilippoOggionni** [comment]
I am also a bit undecided about the naming. Which term should we use? e.g. environment:
-  setup
- modeling
- properties
- etc...

**Comment by DominicDirkx** [comment]
I've pushed a few small modifications (accidentally posted my reply in Slack: https://tudat.slack.com/archives/C01SAUUR6Q5/p1636224816001700, old habits die hard....)

**Comment by DominicDirkx** [comment]
For the page that has been written, I think it should be Environment _Setup_ The TOC tree is for sure fixable, we'll sort it out later.

I made one somewhat significant change to the organization of the pages, and have pushed them to your branch. If you agree with this, you can go ahead and merge this into the master!

I _really_ appreciate the initiative you have shown with this. With this setup, the documentation has become more clear, and also more easily maintained/scaled

**Comment by FilippoOggionni** [comment]
Thanks for reviewing and making the necessary modifications. 

- Removing the split between running the simulation and getting the output is a very nice idea, at least for the time being.
- I have not yet touched the integration setup page, so what we have there was there from before. Regarding this, I agree that merging the intergration setup page with the integrator settings page would be the way to go (not urgent, but better to get it done before Assignment 3 of Numerical Astrodynamics, right?). In addition, thanks to the API documentation, the integration settings page can be somehow shortened, similarly to what we did for the lists of environment and acceleration models.
- I posted a link to the modifiable versions of the diagrams on Slack (this issue is not private).
- I had a quick look to see if I could extend the depth of the TOC tree. To do this, we need to include the following code (specifically, this is included under the "Inputs" paragraph of "State Propagation"):

```
.. toctree::
   :titlesonly:
   :maxdepth: 1

   state_propagation/environment_modeling
   state_propagation/dynamical_modeling
   state_propagation/numerical_modeling
```

There are a couple of issues:
- if we include the `:hidden:` option, then the TOC tree does not show
- the `:titlesonly:` option does not seem to be working.
Attached you can see a screenshot of the output. As you can see, all the paragraphs of environment modeling are included, but I would like to exclude them (indeed, I tried with `:titlesonly:` but unsuccessfully). Besides this small issue, I would stop at the environment/propagation/integration level and I would not go deeper than that. That would mean including in the TOC tree also the separate pages of creating celestial/artificial bodies, etc... In my opinion, that would be a bit too much, but I am curious to hear your opinion @DominicDirkx.

Screen Shot 2021-11-07 at 22 20 25

I pushed my latest changes and I will merge the branch now. I am also liking how the user guide is starting to look like! 🚀

**Pull request merged**
