### PR TITLE
Reorganization of integrator settings 

### PR DESCRIPTION
**Pull request by FilippoOggionni**
See #37.

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Thanks, my bad for not opening this :)

**Comment by FilippoOggionni** [comment]
No worries, I am developing a (dangerous) sense of satisfaction in opening pull requests... Which makes me think I should stay away from my laptop for a while 😅 

The structure looks good to me! I have pushed a couple of minor changes.

Also, given the nature of the content of this page (quite technical, although the page does not - rightfully - go into much detail), I would add a box at the bottom with a short list of references for users who want to read more about the topic (e.g., "Numerical recipes in C++", the tudat technical documentation, and/or similar). Now that I think about it, this could be something that could fit nicely on other selected pages as well...

**Comment by FilippoOggionni** [comment]
That is a good idea! I am not sure what is the best way to achieve that with Sphinx. The simplest option would be to have a separate page with references and we can link the references from different locations, as we do with regular sphinx interlinking. Otherwise, there is an actual sphinx bibliography entry (see this [link](https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#citations)), but I think that would not have the advantage of a "centralized" list of reference, because with that command the bibliography item must go at the bottom of the page it is cited in.

**Comment by DominicDirkx** [comment]
Separate issue opened for the issue of bibliography

**Pull request merged**
