### PR TITLE
Use submodule for example notebooks

### PR DESCRIPTION
**Pull request by larshinueber**
This PR replaces the local jupyter notebooks for the examples shown on the website with the tudatpy-examples repo as a submodule.
Changes made:
- Remove local .ipynb and input/output files
- Add [`tudatpy-examples`](https://github.com/tudat-team/tudatpy-examples) as submodule
- Update `.readthedocs.yml` to include all submodules when cloning the repo
- Update paths in `.rst` and `conf.py` files

If there is any feedback on the approach (see #109 for the issue and https://github.com/tudat-team/tudatpy-examples/issues/13#issuecomment-2298717242 for the proposed workflow) please let me know!

# Before merging
Please review and merge #145 first, as this branch builds on top of this

### CODE REVIEW

**Comment by DominicDirkx** [comment]
This looks good! Great to have this in there as a submodule :) One small note: the README should be updated to reflect the fact that the submodules should be initialized after pulling this repo, using (or similar):
`git submodule update --init --recursive
`

**Comment by larshinueber** [comment]
Hi Dominic,

Thanks for the feedback, I just added the submodule instructions to the README in https://github.com/tudat-team/tudat-space/pull/148/commits/beeae9a3548d3b1cd24071f60d321dd186821f62 :)

Unfortunately I haven't tested the online build yet, I couldn't figure out how to trigger the doc builds manually for versions other than the latest and stable release. Does this need to be initiated from the readthedocs website?

**Comment by DominicDirkx** [comment]
Thanks! On the readthedocs website, you can trigger the build of any branch (I think), to test if it works. I'll have a look at it in the coming days (so many pull requests to go through! :) )

**Comment by DominicDirkx** [comment]
Tested: https://docs.tudat.space/en/feature-examples-submodule/index.html Works like a charm :)

**Comment by larshinueber** [comment]
Great to see this working as intended :)
Do you have any hints on how to trigger the build manually on readthedocs? I couldn't find a way, maybe this is only possible for maintainers on readthedocs?

**Comment by DominicDirkx** [comment]
I have an option 'activate a version' here:

https://readthedocs.org/projects/tudat-space/versions/

Where I can trigger a build for any branch or tag

**Comment by larshinueber** [comment]
Oh I see, I'm missing this option:

image

Nothing of concern of course, maybe we could add this to the developer docs :)

**Pull request merged**
