### PR TITLE
Split asteroid orbit optimization example in three parts.

### PR DESCRIPTION
**Pull request by sbcowan**
The Asteroid Orbit Optimization example is split into three parts that build on each other. I changed the toc in [examples.rst](https://github.com/tudat-team/tudat-space/commit/3a00a59a9348e5de85aa2d821703e1cbaab70db2#diff-01e8fa9b28f3e9cba8ec2760ed643252f17fdb9cc86187de89687de91986cc71) so that now the three files are given and not duplicated. I haven't figured out how to add a directory to a Jupyterlab only sphinx directory; this would allow a foldable directory for the Asteroid Orbit Optimization example.

I left the [old complete file](https://github.com/tudat-team/tudat-space/blob/3a00a59a9348e5de85aa2d821703e1cbaab70db2/docs/source/_src_getting_started/_src_examples/notebooks/pygmo/asteroid_orbit_optimization.ipynb) in the source, if one would want to look at that or revert easily.

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi Sean, thanks! For now we can keep the structure of the examples as you have them. Could you open an issue here to remind us to look into the foldable directory for the asteroid example?

Below a few small comments and questions on the examples:
* The first one now ends with the full creation of the environment, and is rather comparatively short (and has no visualization). Th other two much longer and 'heavy' on results by comparison. Perhaps a simple state propagation could be added to the first one (outcome: hey, look how perturbed this orbit is!), which would shorten the other ones a bit, since the propagation setup is then already documented in the first one.
* The 'problem definition' is very good to have for the second and third one, but is not relevant in its entirety for the first one. The example should also be accessible for people who 'only' want to learn about a custom environment. I think it would flow better without direct mention of decision variables, objectives (but only for the first example!)
* The orth_arrays functions is very long, and also generally written. I forgot if we discussed it previously, but could this not be moved to tudatpy itself (was the issue the difficulty in testitng)? The same goes for yates_array and anova_analysis. This need not delay the merge of these examples, but I think it would be good to open an issue to remind us to do this.
* I think the optimization example would be more effective with all the stuff for design space exploration removed (the two are never really merged in plotting right?)

**Comment by sbcowan** [comment]
> Perhaps a simple state propagation could be added to the first one

I think this is a good solution to the short-vs-very-long example problem. This would probably mean moving the Optimisation problem formulation section in the DSE part of the example to the Custom Environment part. One issue with this is that the `AsteroidProblem` class is used, and already introducing this in the Custom Environment part would be exceeding the reach of that example. I think this is the best solution possible, but it wouldn't result in the simplest state propagation. 

> I think it would flow better without direct mention of decision variables, objectives (but only for the first example!)

Agreed. I will implement this.

> I forgot if we discussed it previously, but could this not be moved to tudatpy itself (was the issue the difficulty in testitng)?

I have done this, a pull request is imminent, however I am in the process of verifying that the tudatpy build works. I have tried building the bundle with the changes, but it didn't work. If the current build also fails, I will report back to you for assistance. I can still open an issue if you want, but as posted in Slack, I cannot assign myself yet as 'Assignee' so I didn't want to waste anyones time.

> I think the optimization example would be more effective with all the stuff for design space exploration removed (the two are never really merged in plotting right?)

The two are indeed never really explicitly linked, so this would make the example shorter (assuming the [issue](https://github.com/tudat-team/tudat-space/issues/87) on importing Jupyter notebooks doesn't get resolved shortly). I do think that, maybe in the future, it would be good to link them explicitly by explaining that certain bounds were chosen based on the findings of the DSE. If we completely decouple them, I think many users will brush over the DSE part of the example. I am unsure if that makes a difference. Let me know and I can implement this change as well.

**Comment by DominicDirkx** [comment]
> I think this is a good solution to the short-vs-very-long example problem. This would probably mean moving the Optimisation problem formulation section in the DSE part of the example to the Custom Environment part. One issue with this is that the AsteroidProblem class is used, and already introducing this in the Custom Environment part would be exceeding the reach of that example. I think this is the best solution possible, but it wouldn't result in the simplest state propagation.

That's true, but I think it's fine. For those who want to know how to set up a custom environment, they can look at the first half, which is there. Adding the problem class and propagation may also be a good introduction into writing a problem class for an optimization with Tudat in the loop.

> I have done this, a pull request is imminent, however I am in the process of verifying that the tudatpy build works. I have tried building the bundle with the changes, but it didn't work. If the current build also fails, I will report back to you for assistance. I can still open an issue if you want, but as posted in Slack, I cannot assign myself yet as 'Assignee' so I didn't want to waste anyones time.

Thanks, I wasn't sure which of these functions were on the short-term list of incorporation into tudatpy. I think if I change your github rights, you can add yourself as assignee. I'll look into it

> The two are indeed never really explicitly linked, so this would make the example shorter (assuming the https://github.com/tudat-team/tudat-space/issues/87 on importing Jupyter notebooks doesn't get resolved shortly). I do think that, maybe in the future, it would be good to link them explicitly by explaining that certain bounds were chosen based on the findings of the DSE. If we completely decouple them, I think many users will brush over the DSE part of the example. I am unsure if that makes a difference. Let me know and I can implement this change as well.

The direct link between the two will most certainly be addressed in P&O :) For now, having the example applications separate won't be an issue for the normal user. I do suspect that more people will use the optimization example, but that's fine. Having the DSE example there will make all this functionality much more visible.

**Comment by DominicDirkx** [comment]
Does this make #82 outdated?

**Comment by sbcowan** [comment]
Okay I'll implement the changes you suggested.

> Does this make https://github.com/tudat-team/tudat-space/pull/82 outdated?

The #82 pull request was already merged into master without explicitly merging the pull request, so yes that pull request is obsolete. This pull request is a follow-up (but will be changed by me again soon).

**Comment by DominicDirkx** [comment]
Thanks, clear, usually it updates the pull request automatically if it gets merged (even if this is done elsewhere)

**Comment by DominicDirkx** [comment]
Hi Sean, thanks! One thing, I may not have made my opinion very clear in my previous post, but I think it would be better to remove the DSE stuff from the optimization example, and have the DSE and optimization examples separate. Could you make this small modification? Other than that, this look really nice!

**Comment by sbcowan** [comment]
That is a mistake, I did remove that, but I guess saving in Jupyterlab somehow didn't go through. I will correct that now.

**Comment by sbcowan** [comment]
The mistake has been resolved.

**Comment by DominicDirkx** [comment]
And merged :)

**Pull request merged**
