### PR TITLE
WSL Guide

### PR DESCRIPTION
**Pull request by larshinueber**
This PR adds a guide on how to setup WSL and configure it to use it with TudatPy.
Let me know if anything is unclear, too long or needs more attention :)

### CODE REVIEW

**Comment by DominicDirkx** [comment]
This is great, thanks! Could you also modify the installation guide to state that Windows users should use this workflow (e.g. install the conda package in WSL)?

**Comment by larshinueber** [comment]
Thanks, I added a note on that. Let me know if the wording is too strong :)

**Comment by DominicDirkx** [comment]
I made it a little bit stronger :)

**Comment by larshinueber** [comment]
Great! Can be merged from my side 👍

**Pull request merged**
